# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: '\b(venv|\.tox|\.git)/'
    -   id: check-yaml
        exclude: '\b(venv|\.tox|\.git)/'
-   repo: local
    hooks:
    -   id: style
        name: Style
        entry: make
        args: ["style"]
        language: system
        pass_filenames: false
        exclude: '\b(venv|\.tox|\.git)/'
